---
# tasks file for ansible-squid

- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Execute Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Execute RHEL tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Squid
  ansible.builtin.include_tasks: config_squid.yml

- name: Configure Squid transparent proxy
  ansible.builtin.include_tasks: config_squid_transparent_proxy.yml
  when:
    - squid_transparent_proxy
    - squid_transparent_proxy_ferm
